name = "nexo-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "NEXO_KV"
id = ""  # Se crea con wrangler kv:namespace create

[env.production]
vars = { ENVIRONMENT = "production" }
